# BookEditor Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/BookEditor

#==================#
#   Basic Config   #
#==================#
# none :3

#==================#
#   Vault Config   #
#==================#
# Hook to Vault for economy integration
UseVault: false
# Costs
Cost:
  Copy: 100
  Edit: 100
  Title: 100
