# BookEditor Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/BookEditor

#==================#
#   Basic Config   #
#==================#
# Hook to Vault for economy integration
UseVault: true
