##  Plugin Information  ##
name: BookEditor
version: version-number-unknown
main: syam.BookEditor.BookEditor
description: BookEditor Plugin
website: http://sakura-server.net/
softdepend: [Vault]
##  Original Author     ##
author: syam
commands:
    book:
      usage: /book - to see the help
      aliases: [be]
      description: To see the BookEditor help.
permissions:
    bookeditor.*:
        default: op
        description: Allow access to all commands
        children:
            bookeditor.user.*: true
            bookeditor.free.*: true
            bookeditor.other.*: true
            bookeditor.setauthor: true
            bookeditor.reload: true
    bookeditor.user.*:
        default: op
        description: Allow access to user commands
        children:
            bookeditor.user.copy: true
            bookeditor.user.edit: true
            bookeditor.user.title: true
            bookeditor.user.title.color: true
    bookeditor.free.*:
        default: op
        description: Bypass all charges
        children:
            bookeditor.free.copy: true
            bookeditor.free.edit: true
            bookeditor.free.title: true
    bookeditor.other.*:
        default: op
        description: Allow use commands to other's book
        children:
            bookeditor.other.copy: true
            bookeditor.other.edit: true
            bookeditor.other.title: true
    bookeditor.user.copy:
        default: op
        description: Allow use copy command
    bookeditor.free.copy:
        default: op
        description: Bypass copy command charge
    bookeditor.other.copy:
        default: op
        description: Allow copy other's book
    bookeditor.user.edit:
        default: op
        description: Allow use edit command
    bookeditor.free.edit:
        default: op
        description: Bypass edit command charge
    bookeditor.other.edit:
        default: op
        description: Allow unsign other's book
    bookeditor.user.title:
        default: op
        description: Allow use title command
    bookeditor.user.title.color:
        default: op
        description: Allow use color tag in title
    bookeditor.free.title:
        default: op
        description: Bypass title command charge
    bookeditor.other.title:
        default: op
        description: Allow edit title other's book
    bookeditor.setauthor:
        default: op
        description: Allow set author the book
    bookeditor.reload:
        default: op
        description: Allow reload configuration