##  Plugin Information  ##
name: BookEditor
version: 0.1
main: syam.BookEditor.BookEditor
description: BookEditor Plugin
website: http://sakura-server.net/
depend: [Vault]
##  Original Author     ##
author: syam
commands:
    book:
      usage: /book - to see the help
      aliases: [be]
      description: To see the BookEditor help.
permissions:
    bookeditor.admin:
        default: op
        description: Allow access to all command
        children:
            bookeditor.copy: true
            bookeditor.copy.free: true
            bookeditor.copy.other: true
            bookeditor.reload: true
    bookeditor.user:
        default: op
        description: Allow access to user command
        children:
            bookeditor.copy: true
    bookeditor.copy:
        default: op
        description: Allow use copy command
    bookeditor.copy.free:
        default: op
        description: Bypass copy command charge
    bookeditor.copy.other:
        default: op
        description: Allow copy other's book
    bookeditor.reload:
        default: op
        description: Allow reload configuration